plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
base = "//"
command = "npm run build"
commandOrigin = "ui"

  [build.environment]
  NODE_VERSION = "16"

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[edge_functions]]
path = "/demo"
function = "EdgeFunction"