plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
base = "D://Repo//React-App"
command = "npm run build"
commandOrigin = "ui"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]